apiVersion: v1
kind: Service
metadata:
  name: speedi-web
  labels:
    app: speedi-web
spec:
  type: NodePort
  selector:
    app: speedi-web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
