apiVersion: v1
kind: Service
metadata:
  name: soursd-web
  labels:
    app: soursd-web
spec:
  type: NodePort
  selector:
    app: soursd-web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
