name: Build and deploy to DEV
run-name: ${{ github.actor }} triggered deploy to DEV pipeline

on:
  push:
    branches:
      - feat/registry-2826

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      docker_build_args: ${{ steps.args.outputs.docker_build_args }}
    steps:
      - id: args
        run: |
          ARGS=""
          ARGS+="--build-arg NEXT_PUBLIC_API_V1_URL=${{ vars.NEXT_PUBLIC_API_V1_URL }} "
          ARGS+="--build-arg NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }} "
          ARGS+="--build-arg NEXT_MIRAGE_SERVER=${{ vars.NEXT_MIRAGE_SERVER }} "
          ARGS+="--build-arg NEXT_PUBLIC_TEMP_USER_ROLES=${{ vars.NEXT_PUBLIC_TEMP_USER_ROLES }} "
          ARGS+="--build-arg NEXT_PUBLIC_INVITE_TIME_HOURS=${{ vars.NEXT_PUBLIC_INVITE_TIME_HOURS }} "
          ARGS+="--build-arg NEXT_PUBLIC_FILE_DOWNLOAD_URL=${{ vars.NEXT_PUBLIC_FILE_DOWNLOAD_URL }} "
          ARGS+="--build-arg NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=${{ vars.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID }} "
          ARGS+="--build-arg NEXT_PUBLIC_KEYCLOAK_CLIENT_SECRET "
          ARGS+="--build-arg NEXT_PUBLIC_KEYCLOAK_REDIRECT_URL_LOGIN=${{ vars.NEXT_PUBLIC_KEYCLOAK_REDIRECT_URL_LOGIN }} "
          ARGS+="--build-arg NEXT_PUBLIC_KEYCLOAK_REDIRECT_URL_LOGOUT=${{ vars.NEXT_PUBLIC_KEYCLOAK_REDIRECT_URL_LOGOUT }} "
          ARGS+="--build-arg NEXT_PUBLIC_KEYCLOAK_REDIRECT_URL_REGISTER=${{ vars.NEXT_PUBLIC_KEYCLOAK_REDIRECT_URL_REGISTER }} "
          ARGS+="--build-arg NEXT_PUBLIC_KEYCLOAK_BASE_URL=${{ vars.NEXT_PUBLIC_KEYCLOAK_BASE_URL }} "
          ARGS+="--build-arg NEXT_PUBLIC_KEYCLOAK_REALM=${{ vars.NEXT_PUBLIC_KEYCLOAK_REALM }} "
          ARGS+="--build-arg NEXT_PUBLIC_KEYCLOAK_TEST_USERNAME=${{ vars.NEXT_PUBLIC_KEYCLOAK_TEST_USERNAME }} "
          ARGS+="--build-arg NEXT_PUBLIC_KEYCLOAK_TEST_PASSWORD "
          ARGS+="--build-arg GOOGLE_MAPS_API_KEY "
          ARGS+="--build-arg NEXT_PUBLIC_LOCAL_ENV=${{ vars.NEXT_PUBLIC_LOCAL_ENV }} "
          ARGS+="--build-arg NEXT_PUBLIC_API_V1_SERVER_URL=${{ vars.NEXT_PUBLIC_API_V1_SERVER_URL }} "
          ARGS+="--build-arg NEXT_PUBLIC_API_SERVER_URL=${{ vars.NEXT_PUBLIC_API_SERVER_URL }} "
          ARGS+="--build-arg NEXT_PUBLIC_GTM_ID=${{ vars.NEXT_PUBLIC_GTM_ID }} "
          ARGS+="--build-arg IDVT_SUPPLIER_BASE_URL=${{ vars.IDVT_SUPPLIER_BASE_URL }} "
          ARGS+="--build-arg IDVT_SUPPLIER_API_KEY "
          echo "docker_build_args=$ARGS" >> "$GITHUB_OUTPUT"

  build:
    needs: setup
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      chart_path: chart/soursd-web/Chart.yaml
      environment: dev
      docker_build_args: ${{ needs.setup.outputs.docker_build_args }}
    secrets: inherit

  deploy:
    needs: build
    uses: HDRUK/github-actions-templates/.github/workflows/deploy-release.yml@main
    with:
      env: dev
      chart_path: chart/soursd-web/Chart.yaml
      git_ref: feat/registry-2826
    secrets: inherit
