name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: main
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Read VERSION file
        id: getversion
        run: |
          sed -n 's/^appVersion:\(.*\)/\1/p' < chart/soursd-web/Chart.yaml > version
          echo "version=$(sed '/.*\"\(.*\)\".*/ s//\1/g' version)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run lint
        run: npm run lint

      # - name: Change package version
      #   run: npm version ${{ steps.getversion.outputs.version }}

      # - name: Commit package version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #   run: git push — tags origin master

      - name: Release
        env:
          NPM_TOKEN: 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
        run: npm publish
